name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o main .

      - name: Check SSH key format
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa
          head -5 id_rsa
        shell: bash

      - name: Upload via SCP
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "main"
          target: "/home/ec2-user/"
          debug: true

      - name: Restart app via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # ✅ Create .env file
            echo "CONNECTION_STRING='${{ secrets.CONNECTION_STRING }}'" > /home/ec2-user/.env

            # ✅ Kill old process if any
            pkill main || true

            # ✅ Start app with .env loaded
            nohup env $(cat /home/ec2-user/.env | xargs) ./main > app.log 2>&1 &

            export CONNECTION_STRING="${{ secrets.CONNECTION_STRING }}"
